### ISSUE TITLE
The chart is not correct

### ISSUE THREAD

**Issue by C2H6O** [dbof10/android-view-lifecycle#1]
`onAttachedToWindow()` does not get called every time after `onPause()` is called. In fact, `onAttachedToWindow()` is called once, until there's a matching `onDetachedFromWindow()` call.

**Comment by dbof10** [comment]
In the chart, the green block `onResume` represents `Activity Lifecycle` there's an arrow from onPause ->  onResume. However,  there is no **arrow** for  ANY orange block which is `View Lifecycle`.
